<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="2" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Acest text e generat prin log-uri]]>
    </line>
    <line>
      <![CDATA[==============================================================================================]]>
    </line>
    <line>
      <![CDATA[Total Passed: 0(+0), Failures: 1(+1), Skips: 0(+0)]]>
    </line>
    <line>
      <![CDATA[==============================================================================================]]>
    </line>
  </reporter-output>
  <suite started-at="2024-03-14T21:39:33 EET" name="Suite" finished-at="2024-03-14T21:39:53 EET" duration-ms="20006">
    <groups>
    </groups>
    <test started-at="2024-03-14T21:39:33 EET" name="Test" finished-at="2024-03-14T21:39:53 EET" duration-ms="20006">
      <class name="ui.SimpleClass">
        <test-method is-config="true" signature="LaunchDriver()[pri:0, instance:ui.SimpleClass@68878f6d]" started-at="2024-03-14T21:39:33 EET" name="LaunchDriver" finished-at="2024-03-14T21:39:47 EET" duration-ms="14536" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Acest text e generat prin log-uri]]>
            </line>
          </reporter-output>
        </test-method> <!-- LaunchDriver -->
        <test-method signature="launchApp()[pri:0, instance:ui.SimpleClass@68878f6d]" started-at="2024-03-14T21:39:47 EET" name="launchApp" finished-at="2024-03-14T21:39:52 EET" duration-ms="5375" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at ui.ListenerTest.onTestSuccess(ListenerTest.java:16)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:100)
at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:656)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
      </class> <!-- ui.SimpleClass -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
